#!/usr/bin/env bash

if [ -f system.log ]; then
    rm system.log
fi

if [ -z $1 ]; then
    echo "What is your project name?"
    read project_name
    export project_name=$project_name
else
    export project_name=$1
fi

if [ "$2" == "clone" ]; then
    git clone https://github.com/Imagination-Media/docker-magento2 $project_name && cd $project_name;
    echo "Git clone done" >> system.log
fi

if [ ! -d "~/.composer" ]; then
    echo "Creating .compose" >> system.log
fi
if [ ! -d "~/.npm" ]; then
    echo "Creating .npm" >> system.log
fi
if [ ! -d "~/.nvm" ]; then
    echo "Creating .nvm" >> system.log
fi

git config --global core.autocrlf false
git config --global core.eol LF
git config --global core.fileMode false
git config --global diff.renamelimit 5000

echo "Setting folder permissions" >> system.log
sudo chmod -R u+x ./*

echo "Check OS" >> system.log

if [ "$(uname)" == "Darwin" ]; then
    echo "Docker Compose for MacOS" >> system.log
    cp docker-compose-macos.yml docker-compose.yml
    cp docker-sync-macos.yml docker-sync.yml
elif [ "$(uname)" == "cygwin" ] || [ "$(uname)" == "msys" ] || [ "$(uname)" == "win32" ]; then
    echo "Docker Compose for Windows" >> system.log
    cp docker-compose-macos.yml docker-compose.yml
    cp docker-sync-macos.yml docker-sync.yml
else
    echo "Docker Compose for Linux" >> system.log
    cp docker-compose-linux.yml docker-compose.yml
fi

echo "Changing project name on files" >> system.log
sed -i '' -e "s/<project_name>/$project_name/g" docker-compose.yml
sed -i '' -e "s/<project_name>/$project_name/g" docker-sync.yml

clear

#docker-compose pull

echo "Folder permission" >> system.log
chmod -R 777 src

echo "Start the containers" >> system.log
bash start
