#!/usr/bin/env bash

export os=$(uname)

if [ -f system.log ]; then
    rm system.log
fi

if [ -z $1 ]; then
    echo "What is your project name?"
    read project_name
    export project_name=$project_name
else
    export project_name=$1
fi

if [ -z $2 ]; then
    echo "What is your project url?"
    read project_url
    export project_url=$project_url
else
    export project_url=$2
fi

if ! grep -F "$2" /etc/hosts
then
    if [ ! $os == "Linux" ]; then        
        sudo -- sh -c -e "echo '10.254.254.254   $project_url' >> /etc/hosts";
    else
        sudo -- sh -c -e "echo '127.0.0.1   $project_url' >> /etc/hosts";
    fi
fi

if [ "$3" == "clone" ]; then
    git clone https://github.com/Imagination-Media/docker-magento2 $project_name && cd $project_name;
    echo "Git clone done" >> system.log
fi

if [ -d "~/.composer" ]; then
    echo "Creating .compose" >> system.log
    mkdir ~/.composer
fi
if [ -d "~/.npm" ]; then
    echo "Creating .npm" >> system.log
    mkdir ~/.npm
fi
if [ -d "~/.nvm" ]; then
    echo "Creating .nvm" >> system.log
    mkdir ~/.nvm
fi

git config --global core.autocrlf false
git config --global core.eol LF
git config --global core.fileMode false
git config --global diff.renamelimit 5000

echo "Setting folder permissions" >> system.log
sudo chmod -R u+x ./*
sudo chmod -R u+x ~/.composer
sudo chmod -R u+x ~/.npm
sudo chmod -R u+x ~/.nvm

echo "Check OS" >> system.log

echo "Docker Compose for Linux" >> system.log
cp docker-compose-linux.yml docker-compose.yml

echo "Changing project name on files" >> system.log
sed -i '' -e "s/<project_name>/$project_name/g" docker-compose.yml
sed -i '' -e "s/<project_url>/$project_url/g" docker-compose.yml

echo "Nginx conf file" >> system.log
cp images/nginx/config/default.conf.sample images/nginx/config/default.conf

echo "Changing project url on files" >> system.log
sed -i '' -e "s/<project_url>/$project_url/g" images/nginx/config/default.conf

clear

#docker-compose pull

echo "Folder permission" >> system.log
chmod -R 777 src

echo "Start the containers" >> system.log
bash start
