#!/usr/bin/env bash

export os=$(uname)

if [ ! $os == "Linux" ]; then
    sudo ifconfig lo0 alias 10.254.254.254
    docker-sync start
fi

docker-compose up -d && \
version=$(git describe --tags $(git rev-list --tags --max-count=1))
echo "
===================== 🚀 Done 🚀 ===================

      Created by Imagination Media

      v.$version
      Access your new links:

      🌎 Web server: http://localhost/
      ⚙️ PHPMyAdmin: http://localhost:8080
      ✉️ Local emails: http://localhost:8025

===================== 🚀 Done 🚀 ==================="

if [ ! $os == "Linux" ]; then
    docker-sync sync
fi
